name = "ValueHistoriesLH"
uuid = "22e5d595-ed39-402f-9fe9-dc630efecdfd"
authors = ["hendri54 <hendricksl@protonmail.com>"]
version = "0.1.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
